# Generated by Django 5.0.7 on 2024-08-04 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('shop', '0002_alter_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
    ]
