# Generated by Django 5.0.7 on 2024-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_orders_cart_id_orders_grand_total_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('canceled', 'canceled')], max_length=30),
        ),
    ]
