# Generated by Django 5.0.7 on 2024-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address_id',
        ),
        migrations.AddField(
            model_name='items',
            name='product',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='total_rate',
            field=models.IntegerField(default=0),
        ),
    ]
