# Generated by Django 5.0.7 on 2024-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orders_discount_orders_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
