# Generated by Django 5.0.7 on 2024-08-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_orders_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
