# Generated by Django 5.0.7 on 2024-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_orders_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
