# Generated by Django 5.0.7 on 2024-08-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
