# Generated by Django 5.0.7 on 2024-08-11 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0008_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.brand')),
            ],
        ),
    ]
