# Generated by Django 5.0.7 on 2024-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_offer',
            name='new_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_offer',
            name='new_amount',
            field=models.IntegerField(default=0),
        ),
    ]
