# Generated by Django 5.0.7 on 2024-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True)),
                ('offer', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condition', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
