# Generated by Django 5.0.7 on 2024-08-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_user_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
