# Generated by Django 5.0.7 on 2024-08-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_condition_alter_coupon_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_coupons',
            name='refferal_code',
            field=models.CharField(default='123456', max_length=10),
        ),
    ]
