# Generated by Django 5.0.7 on 2024-08-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_user_coupons_refferal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coupons',
            name='refferal_code',
        ),
    ]
