# Generated by Django 5.0.7 on 2024-07-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='connection_id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_name', to='admin_panel.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='connection_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connection', to='admin_panel.connection_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_name', to='admin_panel.type'),
        ),
    ]
