# Generated by Django 5.0.7 on 2024-07-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='product_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product'),
        ),
    ]
