# Generated by Django 5.0.7 on 2024-07-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.product'),
        ),
    ]
