# Generated by Django 5.0.7 on 2024-07-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('pincode', models.CharField(max_length=6)),
                ('locality', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('office', 'Office')], max_length=10)),
            ],
        ),
    ]
