# Generated by Django 5.0.7 on 2024-08-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_user_address_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='refferal_code',
            field=models.CharField(default='123456', max_length=10),
        ),
    ]
