# Generated by Django 5.0.7 on 2024-08-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0009_items_product_status'),
        ('coupon', '0003_alter_coupon_condition_alter_coupon_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.orders')),
            ],
        ),
    ]
