# Generated by Django 5.0.7 on 2024-08-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_report',
            name='order_id',
        ),
    ]
