# Generated by Django 5.0.7 on 2024-08-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
