# Generated by Django 5.0.7 on 2024-08-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_orders_confirm'),
        ('wallet', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_transaction',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.orders'),
        ),
    ]
