# Generated by Django 5.0.7 on 2024-07-25 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='admin_panel.product')),
            ],
        ),
    ]
